/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Application metadata */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Samples */
        get: operations["samples_api_v1_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/samples/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sample Detail */
        get: operations["sample_detail_api_v1_samples__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/samples/{item_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sample Action */
        post: operations["sample_action_api_v1_samples__item_id__actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionRequest */
        ActionRequest: {
            /**
             * Action
             * @default validate
             * @enum {string}
             */
            action: "validate" | "simulate";
            /**
             * Force Failure
             * @default false
             */
            force_failure: boolean;
        };
        /** ActionResponse */
        ActionResponse: {
            /**
             * Action
             * @enum {string}
             */
            action: "validate" | "simulate";
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
            /** Item Id */
            item_id: string;
            /** Message */
            message: string;
            /** Result */
            result: {
                [key: string]: string | number;
            };
            /**
             * Status
             * @enum {string}
             */
            status: "succeeded" | "failed";
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            /** Code */
            code: string;
            /** Fields */
            fields?: components["schemas"]["FieldError"][];
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
        };
        /** FieldError */
        FieldError: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /** HealthMeta */
        HealthMeta: {
            /** App Name */
            app_name: string;
            /** Features */
            features: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Version */
            version: string;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Service */
            service: string;
            /** Status */
            status: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** SampleDetail */
        SampleDetail: {
            /** Attributes */
            attributes: {
                [key: string]: string | number | null;
            };
            /** Code */
            code: string;
            /** Description */
            description: string;
            /** Id */
            id: string;
            metrics: components["schemas"]["SampleMetrics"];
            /** Missing Fields */
            missing_fields?: string[];
            /** Owner */
            owner: string;
            /** Score */
            score: number;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "processing" | "attention" | "archived";
            /** Subtitle */
            subtitle?: string | null;
            /** Tags */
            tags: string[];
            /** Title */
            title: string;
            /** Traceback */
            traceback?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SampleListResponse */
        SampleListResponse: {
            /** Items */
            items: components["schemas"]["SampleSummary"][];
            /** Missing Sources */
            missing_sources?: string[];
            /**
             * Partial
             * @default false
             */
            partial: boolean;
            /** Total */
            total: number;
        };
        /** SampleMetrics */
        SampleMetrics: {
            /** Executions */
            executions: number;
            /** Median Duration Ms */
            median_duration_ms: number;
            /** Success Rate */
            success_rate: number;
        };
        /** SampleSummary */
        SampleSummary: {
            /** Id */
            id: string;
            /** Missing Fields */
            missing_fields?: string[];
            /** Owner */
            owner: string;
            /** Score */
            score: number;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "processing" | "attention" | "archived";
            /** Subtitle */
            subtitle?: string | null;
            /** Tags */
            tags: string[];
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthMeta"];
                };
            };
        };
    };
    samples_api_v1_samples_get: {
        parameters: {
            query?: {
                q?: string | null;
                status?: ("ready" | "processing" | "attention" | "archived") | null;
                sort?: "updated" | "score" | "title";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleListResponse"];
                };
            };
            /** @description A requested sample was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description One or more request values are invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description An unexpected server error occurred. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A transient dependency is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    sample_detail_api_v1_samples__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleDetail"];
                };
            };
            /** @description A requested sample was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description One or more request values are invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description An unexpected server error occurred. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A transient dependency is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    sample_action_api_v1_samples__item_id__actions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description A requested sample was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description One or more request values are invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description An unexpected server error occurred. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A transient dependency is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
